name: Test Python Package

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: [actions/checkout](https://github.com/hyperiongeo/natural-neighbor-interpolation)@v4

      - name: Set up Python
        uses: [actions/setup-python](https://github.com/actions/setup-python)@v5
        with:
          python-version: '3.13'
          # Automatically caches dependencies from pyproject.toml
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test] # Installs the package + optional test deps

      - name: Run tests
        run: pytest
